### ISSUE TITLE
is this repo still in maintainance

### ISSUE THREAD

**Issue by zhusihan-python** [matthewcrews/fast-fsharp#2]
Hello sir: 
    I wonder is there any updates about this book, I'm interested in the chapter 11 Data-Oriented Design: Some ideas on how to layout data that is both F# friendly but high-performance and chapter 12 SIMD: How to use SSE/AVX instructions from F# and when to use them

**Comment by matthewcrews** [comment]
I actually need to get rid of this repo as I am no longer working in F# and don't feel qualified to produce this.
